#!/usr/bin/env bash

# From:
# https://github.com/Airblader/dotfiles-manjaro/blob/6c0b9dd49a0647e8d0e3e474a6406189468d6c62/.i3/i3exit

lock() {
    $HOME/.config/i3lock/i3lock.sh
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
